language: ruby
rvm:
- 2.2.10
- 2.3.8
- 2.4.5
- 2.5.3
- 2.6.1
before_install:
- gem install bundler
- gem update --system
before_script:
- bundle exec appraisal install
cache: bundler
script: bundle exec appraisal rspec
