name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1' ]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.1.4
          bundler-cache: true
      - name: Set up Appraisal
        run: bundle exec appraisal update
      - name: Test
        env:
          CI: "true"
        run: bundle exec appraisal rspec
