name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1' ]
        rails: [ '5.0', '5.1', '5.2', '6.0', '6.1', '7.0' ]
        exclude:
          - ruby: '2.6'
            rails: '7.0'
          - ruby: '2.7'
            rails: '7.0'
          - ruby: '3.0'
            rails: '5.0'
          - ruby: '3.0'
            rails: '5.1'
          - ruby: '3.0'
            rails: '5.2'
          - ruby: '3.1'
            rails: '5.0'
          - ruby: '3.1'
            rails: '5.1'
          - ruby: '3.1'
            rails: '5.2'
          - ruby: '3.1'
            rails: '6.0'

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Set up Appraisal
        run: bundle exec appraisal generate
      - name: Install gems
        env:
          BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile"
        run: bundle update
      - name: Test
        env:
          CI: "true"
          BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile"
        run: bundle exec rspec
