name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0', '3.1' ]
        bundler: [ '1.17.3', '2.1.4' ]
        exclude:
          - ruby: '2.5'
            bundler: '2.1.4'
          - ruby: '2.6'
            bundler: '2.1.4'
          - ruby: '2.7'
            bundler: '1.17.3'
          - ruby: '3.0'
            bundler: '1.17.3'
          - ruby: '3.1'
            bundler: '1.17.3'

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true

      - name: Set up Bundler
        run: |
          export BUNDLER_VERSION=${{ matrix.bundler }}
          export BUNDLE_PATH=$PWD/vendor/bundle

          gem update --system

          bundle _${{ matrix.bundler }}_ config set path $PWD/$BUNDLE_PATH
          bundle _${{ matrix.bundler }}_ install --jobs=4 --retry=3
          bundle _${{ matrix.bundler }}_ update
      - name: Set up Appraisal
        run: bundle exec appraisal update
      - name: Test
        env:
          CI: "true"
        run: bundle exec appraisal rspec
